// Local "API" Database - Full Roster (Expanded)
const fightersDB = [
    // Heavyweight
    "Jon Jones", "Tom Aspinall", "Ciryl Gane", "Sergei Pavlovich", "Curtis Blaydes", "Jailton Almeida", "Alexander Volkov", "Serghei Spivac", 
    "Stipe Miocic", "Tai Tuivasa", "Marcin Tybura", "Derrick Lewis", "Jairzinho Rozenstruik", "Alexandr Romanov", "Marcos Rogerio de Lima", 
    "Rodrigo Nascimento", "Waldo Cortes-Acosta", "Mick Parkin", "Valter Walker", "Robelis Despaigne", "Karl Williams", "Martin Buday", 
    "Caio Machado", "Thomas Petersen", "Mohammed Usman", "Austen Lane", "Jhonata Diniz", "Hamdy Abdelwahab", "Chris Barnett", "Jamal Pogues", 
    "Shamil Gaziev", "Don'Tale Mayes", "Lukasz Brzeski",
    
    // Light Heavyweight
    "Alex Pereira", "Jiri Prochazka", "Jamahal Hill", "Magomed Ankalaev", "Jan Blachowicz", "Aleksandar Rakic", "Nikita Krylov", 
    "Khalil Rountree Jr.", "Volkan Oezdemir", "Johnny Walker", "Ryan Spann", "Azamat Murzakanov", "Anthony Smith", "Alonzo Menifield", 
    "Dustin Jacoby", "Kennedy Nzechukwu", "Bogdan Guskov", "Oumar Sy", "Rodolfo Bellato", "Vitor Petrino", "Ibo Aslan", "Zhang Mingyang", 
    "Philipe Lins", "Ion Cutelaba", "Nicolae Negumereanu", "Carlos Ulberg", "Dominick Reyes", "Jimmy Crute", "Modestas Bukauskas",
    
    // Middleweight
    "Dricus Du Plessis", "Sean Strickland", "Israel Adesanya", "Robert Whittaker", "Nassourdine Imavov", "Jared Cannonier", "Marvin Vettori", 
    "Brendan Allen", "Paulo Costa", "Jack Hermansson", "Khamzat Chimaev", "Michel Pereira", "Caio Borralho", "Roman Dolidze", "Anthony Hernandez", 
    "Chris Curtis", "Joe Pyfer", "Gregory Rodrigues", "Ikram Aliskerov", "Shara Magomedov", "Bo Nickal", "Paul Craig", "Andre Muniz", 
    "Gerald Meerschaert", "Bruno Silva", "Cesar Almeida", "Armen Petrosyan", "Christian Leroy Duncan", "Brunno Ferreira", "Nursulton Ruziboev", 
    "Sedriques Dumas", "Zachary Reese", "Robert Bryczek", "Sharabutdin Magomedov", "Rodolfo Vieira", "Marc-Andre Barriault", "Julian Marquez",
    
    // Welterweight
    "Belal Muhammad", "Leon Edwards", "Kamaru Usman", "Shavkat Rakhmonov", "Jack Della Maddalena", "Colby Covington", "Ian Machado Garry", 
    "Gilbert Burns", "Sean Brady", "Stephen Thompson", "Geoff Neal", "Vicente Luque", "Michael Morales", "Michael Page", "Rafael dos Anjos", 
    "Kevin Holland", "Rinat Fakhretdinov", "Randy Brown", "Joaquin Buckley", "Daniel Rodriguez", "Neil Magny", "Gunnar Nelson", "Nicolas Dalby", 
    "Elizeu Zaleski dos Santos", "Gabriel Bonfim", "Khaos Williams", "Carlos Prates", "Danny Barlow", "Themba Gorimbo", "Trey Waters", 
    "Oban Elliott", "Ange Loosa", "Preston Parsons", "Bassil Hafez", "Santiago Ponzinibbio", "Muslim Salikhov", "Bryan Battle",
    
    // Lightweight
    "Islam Makhachev", "Arman Tsarukyan", "Charles Oliveira", "Justin Gaethje", "Dustin Poirier", "Michael Chandler", "Mateusz Gamrot", 
    "Beneil Dariush", "Renato Moicano", "Max Holloway", "Dan Hooker", "Benoit Saint Denis", "Jalin Turner", "Rafael Fiziev", "Paddy Pimblett", 
    "Bobby Green", "King Green", "Grant Dawson", "Drew Dober", "Joel Alvarez", "Matt Frevola", "Thiago Moises", "Nasrat Haqparast", 
    "Jared Gordon", "Vinc Pichel", "Ludovit Klein", "Ignacio Bahamondes", "Manuel Torres", "Elves Brener", "Kaynan Kruschewsky", 
    "Marquel Mederos", "Esteban Ribovics", "Mauricio Ruffy", "Myktybek Orolbai", "Terrance McKinney", "Clay Guida", "Jim Miller", 
    "Landon Quinones", "Roosevelt Roberts",
    
    // Featherweight
    "Ilia Topuria", "Alexander Volkanovski", "Max Holloway", "Brian Ortega", "Yair Rodriguez", "Movsar Evloev", "Arnold Allen", "Josh Emmett", 
    "Aljamain Sterling", "Calvin Kattar", "Giga Chikadze", "Bryce Mitchell", "Diego Lopes", "Edson Barboza", "Dan Ige", "Lerone Murphy", 
    "Sodiq Yusuff", "Nathaniel Wood", "Jonathan Pearce", "Joanderson Brito", "Billy Quarantillo", "Julian Erosa", "Charles Jourdain", 
    "Pat Sabatini", "Ricardo Ramos", "Jack Jenkins", "William Gomis", "Isaac Dulgarian", "Hyder Amil", "Westin Wilson", "Jeka Saragih", 
    "Yi Zha", "Jean Silva", "Cub Swanson", "Doo Ho Choi", "Andre Fili", "Alex Caceres",
    
    // Bantamweight
    "Sean O'Malley", "Merab Dvalishvili", "Cory Sandhagen", "Petr Yan", "Marlon Vera", "Henry Cejudo", "Deiveson Figueiredo", "Song Yadong", 
    "Rob Font", "Mario Bautista", "Jonathan Martinez", "Kyler Phillips", "Dominick Cruz", "Pedro Munhoz", "Umar Nurmagomedov", "Montel Jackson", 
    "Said Nurmagomedov", "Youssef Zalal", "Raul Rosas Jr.", "Payton Talbott", "Cameron Saaiman", "Farid Basharat", "Javid Basharat", 
    "Taylor Lapilus", "Daniel Marcos", "Vinicius Oliveira", "Ricky Turcios", "Cody Garbrandt", "Miles Johns", "Da'Mon Blackshear", 
    "Aiemann Zahabi", "Marcus McGhee", "Rani Yahya", "Kyung Ho Kang", "Davey Grant", "Chris Gutierrez",
    
    // Flyweight
    "Alexandre Pantoja", "Brandon Royval", "Brandon Moreno", "Amir Albazi", "Kai Kara-France", "Matheus Nicolau", "Tatsuro Taira", 
    "Manel Kape", "Steve Erceg", "Tim Elliott", "Tagir Ulanbekov", "Alex Perez", "Matt Schnell", "Cody Durden", "Sumudaerji", 
    "David Dvorak", "Charles Johnson", "Azat Maksum", "Joshua Van", "Felipe dos Santos", "Bruno Silva", "Allan Nascimento", "Jafel Filho", 
    "Assu Almabayev", "Park Hyun-sung", "Rei Tsuruya", "Igor Severino", "Andre Lima", "Clayton Carpenter",
    
    // Women's Divisions
    "Zhang Weili", "Alexa Grasso", "Valentina Shevchenko", "Manon Fiorot", "Erin Blanchfield", "Tatiana Suarez", "Rose Namajunas", 
    "Yan Xiaonan", "Amanda Lemos", "Virna Jandiroba", "Raquel Pennington", "Julianna Pena", "Kayla Harrison", "Ketlen Vieira", 
    "Holly Holm", "Irene Aldana", "Macy Chiasson", "Pannie Kianzad", "Karol Rosa", "Norma Dumont", "Mayra Bueno Silva", 
    "Jasmine Jasudavicius", "Natalia Silva", "Karine Silva", "Ariane Lipski", "Casey O'Neill", "Tracy Cortez", "Loopy Godinez", 
    "Tabatha Ricci", "Mackenzie Dern", "Angela Hill", "Gillian Robertson", "Polyana Viana", "Luana Pinheiro", "Emily Ducote", 
    "Miesha Tate", "Tecia Pennington", "Michelle Waterson-Gomez", "Jessica Andrade", "Marina Rodriguez"
];

// Manual Stats Database for Top Fighters (Level 1 Source)
const fighterStatsMap = {
    "Jon Jones": { height: "193cm", reach: "215cm", wins: 28, losses: 1, draws: 0, stance: "Orthodox", nickname: "Bones" },
    "Tom Aspinall": { height: "196cm", reach: "198cm", wins: 15, losses: 3, draws: 0, stance: "Orthodox" },
    "Ciryl Gane": { height: "193cm", reach: "206cm", wins: 12, losses: 2, draws: 0, stance: "Orthodox", nickname: "Bon Gamin" },
    "Stipe Miocic": { height: "193cm", reach: "203cm", wins: 20, losses: 5, draws: 0, stance: "Orthodox" },
    "Derrick Lewis": { height: "191cm", reach: "201cm", wins: 28, losses: 12, draws: 0, stance: "Orthodox", nickname: "The Black Beast" },
    "Sergei Pavlovich": { height: "191cm", reach: "213cm", wins: 18, losses: 3, draws: 0, stance: "Southpaw" },
    "Alex Pereira": { height: "193cm", reach: "201cm", wins: 12, losses: 2, draws: 0, stance: "Orthodox", nickname: "Poatan" },
    "Jiri Prochazka": { height: "191cm", reach: "203cm", wins: 30, losses: 5, draws: 1, stance: "Orthodox", nickname: "BJP" },
    "Jamahal Hill": { height: "193cm", reach: "201cm", wins: 12, losses: 2, draws: 0, stance: "Southpaw", nickname: "Sweet Dreams" },
    "Magomed Ankalaev": { height: "191cm", reach: "191cm", wins: 19, losses: 1, draws: 1, stance: "Orthodox" },
    "Jan Blachowicz": { height: "188cm", reach: "198cm", wins: 29, losses: 10, draws: 1, stance: "Orthodox", nickname: "Prince of Cieszyn" },
    "Nikita Krylov": { height: "191cm", reach: "197cm", wins: 30, losses: 9, draws: 0, stance: "Orthodox", nickname: "The Miner" },
    "Khalil Rountree Jr.": { height: "185cm", reach: "194cm", wins: 13, losses: 5, draws: 0, stance: "Southpaw", nickname: "The War Horse" },
    "Volkan Oezdemir": { height: "185cm", reach: "191cm", wins: 19, losses: 7, draws: 0, stance: "Orthodox", nickname: "No Time" },
    "Johnny Walker": { height: "198cm", reach: "208cm", wins: 21, losses: 8, draws: 0, stance: "Orthodox" },
    "Ryan Spann": { height: "196cm", reach: "201cm", wins: 21, losses: 9, draws: 0, stance: "Orthodox", nickname: "Superman" },
    "Azamat Murzakanov": { height: "178cm", reach: "182cm", wins: 13, losses: 0, draws: 0, stance: "Southpaw", nickname: "The Professional" },
    "Anthony Smith": { height: "193cm", reach: "193cm", wins: 37, losses: 19, draws: 0, stance: "Orthodox", nickname: "Lionheart" },
    "Alonzo Menifield": { height: "183cm", reach: "193cm", wins: 15, losses: 4, draws: 1, stance: "Orthodox", nickname: "Atomic" },
    "Dustin Jacoby": { height: "191cm", reach: "198cm", wins: 19, losses: 8, draws: 1, stance: "Orthodox", nickname: "The Hanyak" },
    "Kennedy Nzechukwu": { height: "196cm", reach: "211cm", wins: 12, losses: 4, draws: 0, stance: "Southpaw", nickname: "African Savage" },
    "Bogdan Guskov": { height: "191cm", reach: "193cm", wins: 15, losses: 3, draws: 0, stance: "Orthodox", nickname: "Tsarevich" },
    "Oumar Sy": { height: "196cm", reach: "213cm", wins: 10, losses: 0, draws: 0, stance: "Orthodox" },
    "Rodolfo Bellato": { height: "191cm", reach: "196cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox" },
    "Vitor Petrino": { height: "188cm", reach: "196cm", wins: 11, losses: 1, draws: 0, stance: "Orthodox", nickname: "Icao" },
    "Ibo Aslan": { height: "191cm", reach: "196cm", wins: 13, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Last Ottoman" },
    "Zhang Mingyang": { height: "188cm", reach: "191cm", wins: 17, losses: 6, draws: 0, stance: "Orthodox", nickname: "Mountain Tiger" },
    "Philipe Lins": { height: "188cm", reach: "198cm", wins: 17, losses: 5, draws: 0, stance: "Orthodox", nickname: "Monstro" },
    "Ion Cutelaba": { height: "185cm", reach: "191cm", wins: 17, losses: 9, draws: 1, stance: "Southpaw", nickname: "The Hulk" },
    "Nicolae Negumereanu": { height: "183cm", reach: "193cm", wins: 13, losses: 2, draws: 0, stance: "Orthodox" },
    "Carlos Ulberg": { height: "193cm", reach: "196cm", wins: 10, losses: 1, draws: 0, stance: "Orthodox", nickname: "Black Jag" },
    "Dominick Reyes": { height: "193cm", reach: "196cm", wins: 13, losses: 4, draws: 0, stance: "Southpaw", nickname: "The Devastator" },
    "Jimmy Crute": { height: "188cm", reach: "185cm", wins: 12, losses: 4, draws: 1, stance: "Orthodox", nickname: "The Brute" },
    "Modestas Bukauskas": { height: "191cm", reach: "198cm", wins: 15, losses: 6, draws: 0, stance: "Switch", nickname: "The Baltic Gladiator" },
    "Dricus Du Plessis": { height: "185cm", reach: "193cm", wins: 23, losses: 3, draws: 0, stance: "Switch", nickname: "Stillknocks" },
    "Sean Strickland": { height: "185cm", reach: "193cm", wins: 30, losses: 6, draws: 0, stance: "Orthodox", nickname: "Tarzan" },
    "Israel Adesanya": { height: "193cm", reach: "203cm", wins: 24, losses: 4, draws: 0, stance: "Switch", nickname: "The Last Stylebender" },
    "Robert Whittaker": { height: "183cm", reach: "185cm", wins: 27, losses: 8, draws: 0, stance: "Orthodox", nickname: "The Reaper" },
    "Khamzat Chimaev": { height: "188cm", reach: "191cm", wins: 15, losses: 0, draws: 0, stance: "Orthodox", nickname: "Borz" },
    "Nassourdine Imavov": { height: "191cm", reach: "192cm", wins: 17, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Sniper" },
    "Caio Borralho": { height: "185cm", reach: "191cm", wins: 17, losses: 2, draws: 0, stance: "Southpaw", nickname: "The Natural" },
    "Marvin Vettori": { height: "183cm", reach: "188cm", wins: 19, losses: 7, draws: 1, stance: "Southpaw", nickname: "The Italian Dream" },
    "Jared Cannonier": { height: "180cm", reach: "196cm", wins: 17, losses: 8, draws: 0, stance: "Switch", nickname: "The Killa Gorilla" },
    "Brendan Allen": { height: "188cm", reach: "191cm", wins: 24, losses: 5, draws: 0, stance: "Orthodox", nickname: "All In" },
    "Roman Dolidze": { height: "188cm", reach: "193cm", wins: 13, losses: 3, draws: 0, stance: "Orthodox", nickname: "The Caucasian" },
    "Paulo Costa": { height: "185cm", reach: "183cm", wins: 14, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Eraser" },
    "Jack Hermansson": { height: "185cm", reach: "196cm", wins: 24, losses: 8, draws: 0, stance: "Orthodox", nickname: "The Joker" },
    "Anthony Hernandez": { height: "183cm", reach: "191cm", wins: 12, losses: 2, draws: 0, stance: "Orthodox", nickname: "Fluffy" },
    "Shara Magomedov": { height: "188cm", reach: "185cm", wins: 15, losses: 0, draws: 0, stance: "Orthodox", nickname: "Bullet" },
    "Michel Pereira": { height: "185cm", reach: "185cm", wins: 31, losses: 11, draws: 0, stance: "Orthodox", nickname: "Demolidor" },
    "Chris Curtis": { height: "178cm", reach: "191cm", wins: 31, losses: 11, draws: 0, stance: "Southpaw", nickname: "The Action Man" },
    "Joe Pyfer": { height: "188cm", reach: "191cm", wins: 13, losses: 3, draws: 0, stance: "Orthodox", nickname: "Bodybagz" },
    "Gregory Rodrigues": { height: "191cm", reach: "191cm", wins: 16, losses: 5, draws: 0, stance: "Orthodox", nickname: "Robocop" },
    "Ikram Aliskerov": { height: "183cm", reach: "193cm", wins: 16, losses: 1, draws: 0, stance: "Southpaw" },
    "Bo Nickal": { height: "185cm", reach: "193cm", wins: 7, losses: 0, draws: 0, stance: "Southpaw", nickname: "The Allen" },
    "Paul Craig": { height: "193cm", reach: "193cm", wins: 17, losses: 8, draws: 1, stance: "Orthodox", nickname: "Bearjew" },
    "Andre Muniz": { height: "185cm", reach: "198cm", wins: 24, losses: 6, draws: 0, stance: "Southpaw", nickname: "Sergipano" },
    "Gerald Meerschaert": { height: "185cm", reach: "196cm", wins: 37, losses: 18, draws: 0, stance: "Southpaw", nickname: "GM3" },
    "Bruno Silva": { height: "183cm", reach: "188cm", wins: 23, losses: 11, draws: 0, stance: "Orthodox", nickname: "Blindado" },
    "Cesar Almeida": { height: "185cm", reach: "191cm", wins: 5, losses: 1, draws: 0, stance: "Orthodox" },
    "Armen Petrosyan": { height: "191cm", reach: "180cm", wins: 9, losses: 3, draws: 0, stance: "Orthodox", nickname: "Superman" },
    "Christian Leroy Duncan": { height: "188cm", reach: "201cm", wins: 10, losses: 1, draws: 0, stance: "Switch", nickname: "CLD" },
    "Brunno Ferreira": { height: "178cm", reach: "183cm", wins: 12, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Hulk" },
    "Nursulton Ruziboev": { height: "196cm", reach: "193cm", wins: 36, losses: 8, draws: 2, stance: "Orthodox", nickname: "Black" },
    "Sedriques Dumas": { height: "188cm", reach: "201cm", wins: 10, losses: 2, draws: 0, stance: "Orthodox", nickname: "The Reaper" },
    "Zachary Reese": { height: "193cm", reach: "196cm", wins: 7, losses: 1, draws: 0, stance: "Switch", nickname: "Savage" },
    "Robert Bryczek": { height: "183cm", reach: "185cm", wins: 17, losses: 6, draws: 0, stance: "Orthodox" },
    "Sharabutdin Magomedov": { height: "188cm", reach: "185cm", wins: 15, losses: 0, draws: 0, stance: "Orthodox", nickname: "Bullet" },
    "Rodolfo Vieira": { height: "183cm", reach: "185cm", wins: 10, losses: 2, draws: 0, stance: "Orthodox", nickname: "The Black Belt Hunter" },
    "Marc-Andre Barriault": { height: "185cm", reach: "188cm", wins: 16, losses: 8, draws: 0, stance: "Orthodox", nickname: "Powerbar" },
    "Julian Marquez": { height: "188cm", reach: "183cm", wins: 9, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Cuban Missile Crisis" },
    "Belal Muhammad": { height: "180cm", reach: "183cm", wins: 24, losses: 3, draws: 0, stance: "Orthodox", nickname: "Remember the Name" },
    "Leon Edwards": { height: "183cm", reach: "188cm", wins: 22, losses: 4, draws: 0, stance: "Southpaw", nickname: "Rocky" },
    "Kamaru Usman": { height: "183cm", reach: "193cm", wins: 20, losses: 4, draws: 0, stance: "Switch", nickname: "The Nigerian Nightmare" },
    "Shavkat Rakhmonov": { height: "185cm", reach: "196cm", wins: 18, losses: 0, draws: 0, stance: "Orthodox", nickname: "Nomad" },
    "Jack Della Maddalena": { height: "180cm", reach: "185cm", wins: 17, losses: 2, draws: 0, stance: "Switch" },
    "Ian Machado Garry": { height: "191cm", reach: "188cm", wins: 15, losses: 0, draws: 0, stance: "Orthodox", nickname: "The Future" },
    "Colby Covington": { height: "180cm", reach: "183cm", wins: 17, losses: 4, draws: 0, stance: "Orthodox", nickname: "Chaos" },
    "Stephen Thompson": { height: "183cm", reach: "191cm", wins: 17, losses: 7, draws: 1, stance: "Orthodox", nickname: "Wonderboy" },
    "Sean Brady": { height: "178cm", reach: "183cm", wins: 17, losses: 1, draws: 0, stance: "Orthodox" },
    "Geoff Neal": { height: "180cm", reach: "191cm", wins: 16, losses: 6, draws: 0, stance: "Southpaw", nickname: "Handz of Steel" },
    "Vicente Luque": { height: "180cm", reach: "191cm", wins: 22, losses: 10, draws: 1, stance: "Orthodox", nickname: "The Silent Assassin" },
    "Michael Morales": { height: "183cm", reach: "201cm", wins: 17, losses: 0, draws: 0, stance: "Orthodox" },
    "Gilbert Burns": { height: "178cm", reach: "180cm", wins: 22, losses: 7, draws: 0, stance: "Orthodox", nickname: "Durinho" },
    "Kevin Holland": { height: "191cm", reach: "206cm", wins: 26, losses: 12, draws: 0, stance: "Orthodox", nickname: "Trailblazer" },
    "Joaquin Buckley": { height: "173cm", reach: "193cm", wins: 20, losses: 6, draws: 0, stance: "Southpaw", nickname: "New Mansa" },
    "Neil Magny": { height: "191cm", reach: "203cm", wins: 29, losses: 12, draws: 0, stance: "Orthodox", nickname: "The Haitian Sensation" },
    "Rafael dos Anjos": { height: "173cm", reach: "178cm", wins: 32, losses: 16, draws: 0, stance: "Southpaw", nickname: "RDA" },
    "Randy Brown": { height: "191cm", reach: "198cm", wins: 19, losses: 5, draws: 0, stance: "Orthodox", nickname: "Rude Boy" },
    "Rinat Fakhretdinov": { height: "183cm", reach: "188cm", wins: 22, losses: 1, draws: 1, stance: "Orthodox", nickname: "Gladiator" },
    "Michael Page": { height: "191cm", reach: "201cm", wins: 22, losses: 3, draws: 0, stance: "Switch", nickname: "MVP" },
    "Daniel Rodriguez": { height: "185cm", reach: "188cm", wins: 18, losses: 5, draws: 0, stance: "Southpaw", nickname: "D-Rod" },
    "Gunnar Nelson": { height: "180cm", reach: "183cm", wins: 19, losses: 5, draws: 1, stance: "Switch", nickname: "Gunni" },
    "Nicolas Dalby": { height: "180cm", reach: "189cm", wins: 23, losses: 5, draws: 1, stance: "Orthodox", nickname: "Danish Dynamite" },
    "Elizeu Zaleski dos Santos": { height: "180cm", reach: "185cm", wins: 24, losses: 8, draws: 1, stance: "Orthodox", nickname: "Capoeira" },
    "Gabriel Bonfim": { height: "185cm", reach: "183cm", wins: 16, losses: 1, draws: 0, stance: "Orthodox", nickname: "Marretinha" },
    "Khaos Williams": { height: "183cm", reach: "196cm", wins: 15, losses: 3, draws: 0, stance: "Orthodox", nickname: "The Oxfighter" },
    "Carlos Prates": { height: "185cm", reach: "198cm", wins: 20, losses: 6, draws: 0, stance: "Switch", nickname: "The Nightmare" },
    "Danny Barlow": { height: "188cm", reach: "201cm", wins: 8, losses: 0, draws: 0, stance: "Southpaw", nickname: "LeftHand2God" },
    "Themba Gorimbo": { height: "185cm", reach: "196cm", wins: 13, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Answer" },
    "Trey Waters": { height: "196cm", reach: "196cm", wins: 9, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Truth" },
    "Oban Elliott": { height: "180cm", reach: "183cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox", nickname: "The Welsh Gangster" },
    "Ange Loosa": { height: "178cm", reach: "188cm", wins: 10, losses: 3, draws: 0, stance: "Orthodox", nickname: "The Last Ninja" },
    "Preston Parsons": { height: "180cm", reach: "180cm", wins: 11, losses: 4, draws: 0, stance: "Orthodox", nickname: "Pressure" },
    "Bassil Hafez": { height: "180cm", reach: "191cm", wins: 9, losses: 4, draws: 1, stance: "Orthodox", nickname: "The Habibi" },
    "Santiago Ponzinibbio": { height: "183cm", reach: "185cm", wins: 29, losses: 7, draws: 0, stance: "Orthodox", nickname: "Argentine Dagger" },
    "Muslim Salikhov": { height: "180cm", reach: "178cm", wins: 20, losses: 5, draws: 0, stance: "Orthodox", nickname: "King of Kung Fu" },
    "Bryan Battle": { height: "185cm", reach: "196cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox", nickname: "The Butcher" },
    "Islam Makhachev": { height: "178cm", reach: "178cm", wins: 26, losses: 1, draws: 0, stance: "Southpaw" },
    "Arman Tsarukyan": { height: "170cm", reach: "183cm", wins: 22, losses: 3, draws: 0, stance: "Orthodox", nickname: "Ahalkalakets" },
    "Charles Oliveira": { height: "178cm", reach: "188cm", wins: 34, losses: 10, draws: 0, stance: "Orthodox", nickname: "Do Bronx" },
    "Justin Gaethje": { height: "180cm", reach: "178cm", wins: 25, losses: 5, draws: 0, stance: "Orthodox", nickname: "The Highlight" },
    "Dustin Poirier": { height: "175cm", reach: "183cm", wins: 30, losses: 9, draws: 0, stance: "Southpaw", nickname: "The Diamond" },
    "Michael Chandler": { height: "173cm", reach: "180cm", wins: 23, losses: 8, draws: 0, stance: "Orthodox", nickname: "Iron" },
    "Mateusz Gamrot": { height: "178cm", reach: "180cm", wins: 24, losses: 2, draws: 0, stance: "Southpaw", nickname: "Gamer" },
    "Beneil Dariush": { height: "178cm", reach: "183cm", wins: 22, losses: 6, draws: 1, stance: "Southpaw", nickname: "Benny" },
    "Renato Moicano": { height: "180cm", reach: "183cm", wins: 19, losses: 5, draws: 1, stance: "Orthodox", nickname: "Money" },
    "Dan Hooker": { height: "183cm", reach: "191cm", wins: 23, losses: 12, draws: 0, stance: "Switch", nickname: "The Hangman" },
    "Benoit Saint Denis": { height: "180cm", reach: "185cm", wins: 13, losses: 2, draws: 0, stance: "Southpaw", nickname: "God of War" },
    "Jalin Turner": { height: "191cm", reach: "196cm", wins: 14, losses: 8, draws: 0, stance: "Southpaw", nickname: "The Tarantula" },
    "Rafael Fiziev": { height: "173cm", reach: "180cm", wins: 12, losses: 3, draws: 0, stance: "Switch", nickname: "Ataman" },
    "Paddy Pimblett": { height: "178cm", reach: "185cm", wins: 21, losses: 3, draws: 0, stance: "Orthodox", nickname: "The Baddy" },
    "Bobby Green": { height: "178cm", reach: "180cm", wins: 32, losses: 15, draws: 1, stance: "Orthodox", nickname: "King" },
    "Grant Dawson": { height: "178cm", reach: "183cm", wins: 21, losses: 2, draws: 1, stance: "Switch", nickname: "KGD" },
    "Drew Dober": { height: "173cm", reach: "178cm", wins: 27, losses: 13, draws: 0, stance: "Southpaw" },
    "Joel Alvarez": { height: "191cm", reach: "196cm", wins: 20, losses: 3, draws: 0, stance: "Orthodox", nickname: "El Fenomeno" },
    "Matt Frevola": { height: "175cm", reach: "180cm", wins: 11, losses: 4, draws: 1, stance: "Orthodox", nickname: "The Steamrolla" },
    "Thiago Moises": { height: "175cm", reach: "178cm", wins: 18, losses: 7, draws: 0, stance: "Orthodox" },
    "Nasrat Haqparast": { height: "178cm", reach: "183cm", wins: 16, losses: 5, draws: 0, stance: "Southpaw" },
    "Jared Gordon": { height: "175cm", reach: "173cm", wins: 20, losses: 6, draws: 0, stance: "Orthodox", nickname: "Flash" },
    "Ludovit Klein": { height: "170cm", reach: "183cm", wins: 22, losses: 4, draws: 1, stance: "Southpaw", nickname: "Mr. Highlight" },
    "Ignacio Bahamondes": { height: "191cm", reach: "191cm", wins: 15, losses: 5, draws: 0, stance: "Orthodox", nickname: "La Jaula" },
    "Manuel Torres": { height: "178cm", reach: "185cm", wins: 15, losses: 2, draws: 0, stance: "Orthodox", nickname: "El Loco" },
    "Elves Brener": { height: "178cm", reach: "183cm", wins: 16, losses: 4, draws: 0, stance: "Orthodox" },
    "Esteban Ribovics": { height: "178cm", reach: "175cm", wins: 13, losses: 1, draws: 0, stance: "Orthodox", nickname: "El Gringo" },
    "Mauricio Ruffy": { height: "180cm", reach: "183cm", wins: 10, losses: 1, draws: 0, stance: "Orthodox" },
    "Myktybek Orolbai": { height: "178cm", reach: "183cm", wins: 13, losses: 1, draws: 1, stance: "Orthodox" },
    "Terrance McKinney": { height: "178cm", reach: "187cm", wins: 15, losses: 6, draws: 0, stance: "Switch", nickname: "T.Wrecks" },
    "Clay Guida": { height: "170cm", reach: "178cm", wins: 38, losses: 24, draws: 0, stance: "Orthodox", nickname: "The Carpenter" },
    "Jim Miller": { height: "173cm", reach: "180cm", wins: 37, losses: 18, draws: 0, stance: "Southpaw", nickname: "A-10" },
    "Landon Quinones": { height: "175cm", reach: "178cm", wins: 7, losses: 2, draws: 1, stance: "Southpaw" },
    "Roosevelt Roberts": { height: "188cm", reach: "185cm", wins: 12, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Predator" },
    "Alexander Volkanovski": { height: "168cm", reach: "180cm", wins: 26, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Great" },
    "Max Holloway": { height: "180cm", reach: "175cm", wins: 26, losses: 8, draws: 0, stance: "Orthodox", nickname: "Blessed" },
    "Brian Ortega": { height: "173cm", reach: "175cm", wins: 16, losses: 4, draws: 0, stance: "Switch", nickname: "T-City" },
    "Yair Rodriguez": { height: "180cm", reach: "180cm", wins: 19, losses: 5, draws: 0, stance: "Switch", nickname: "El Pantera" },
    "Movsar Evloev": { height: "170cm", reach: "184cm", wins: 18, losses: 0, draws: 0, stance: "Orthodox" },
    "Arnold Allen": { height: "173cm", reach: "178cm", wins: 19, losses: 3, draws: 0, stance: "Southpaw", nickname: "Almighty" },
    "Josh Emmett": { height: "168cm", reach: "178cm", wins: 19, losses: 4, draws: 0, stance: "Orthodox" },
    "Aljamain Sterling": { height: "170cm", reach: "180cm", wins: 24, losses: 4, draws: 0, stance: "Orthodox", nickname: "Funk Master" },
    "Calvin Kattar": { height: "180cm", reach: "183cm", wins: 23, losses: 8, draws: 0, stance: "Orthodox", nickname: "The Boston Finisher" },
    "Giga Chikadze": { height: "183cm", reach: "188cm", wins: 15, losses: 4, draws: 0, stance: "Orthodox", nickname: "Ninja" },
    "Bryce Mitchell": { height: "175cm", reach: "178cm", wins: 16, losses: 2, draws: 0, stance: "Southpaw", nickname: "Thug Nasty" },
    "Diego Lopes": { height: "180cm", reach: "184cm", wins: 24, losses: 6, draws: 0, stance: "Orthodox" },
    "Edson Barboza": { height: "180cm", reach: "191cm", wins: 24, losses: 12, draws: 0, stance: "Orthodox", nickname: "Junior" },
    "Dan Ige": { height: "170cm", reach: "180cm", wins: 18, losses: 7, draws: 0, stance: "Orthodox", nickname: "50K" },
    "Lerone Murphy": { height: "175cm", reach: "186cm", wins: 14, losses: 0, draws: 1, stance: "Orthodox", nickname: "The Miracle" },
    "Sodiq Yusuff": { height: "175cm", reach: "180cm", wins: 13, losses: 4, draws: 0, stance: "Orthodox", nickname: "Super" },
    "Nathaniel Wood": { height: "168cm", reach: "175cm", wins: 20, losses: 6, draws: 0, stance: "Orthodox", nickname: "The Prospect" },
    "Jonathan Pearce": { height: "183cm", reach: "180cm", wins: 14, losses: 6, draws: 0, stance: "Switch", nickname: "JSP" },
    "Joanderson Brito": { height: "173cm", reach: "183cm", wins: 17, losses: 3, draws: 1, stance: "Orthodox", nickname: "Tubarao" },
    "Billy Quarantillo": { height: "178cm", reach: "178cm", wins: 18, losses: 6, draws: 0, stance: "Orthodox" },
    "Julian Erosa": { height: "185cm", reach: "189cm", wins: 29, losses: 11, draws: 0, stance: "Southpaw", nickname: "Juicy J" },
    "Charles Jourdain": { height: "175cm", reach: "175cm", wins: 15, losses: 7, draws: 1, stance: "Switch", nickname: "Air" },
    "Pat Sabatini": { height: "173cm", reach: "178cm", wins: 18, losses: 5, draws: 0, stance: "Orthodox" },
    "Ricardo Ramos": { height: "175cm", reach: "183cm", wins: 16, losses: 6, draws: 0, stance: "Orthodox" },
    "Jack Jenkins": { height: "170cm", reach: "173cm", wins: 12, losses: 3, draws: 0, stance: "Switch", nickname: "Phar" },
    "William Gomis": { height: "183cm", reach: "185cm", wins: 13, losses: 2, draws: 0, stance: "Southpaw", nickname: "The Jaguar" },
    "Isaac Dulgarian": { height: "170cm", reach: "180cm", wins: 6, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Midwest Choppa" },
    "Hyder Amil": { height: "175cm", reach: "178cm", wins: 9, losses: 0, draws: 0, stance: "Orthodox", nickname: "The Hurricane" },
    "Westin Wilson": { height: "185cm", reach: "185cm", wins: 17, losses: 9, draws: 0, stance: "Orthodox" },
    "Jeka Saragih": { height: "173cm", reach: "175cm", wins: 14, losses: 3, draws: 0, stance: "Orthodox", nickname: "Si Tendangan Maut" },
    "Yi Zha": { height: "170cm", reach: "173cm", wins: 25, losses: 4, draws: 0, stance: "Orthodox" },
    "Jean Silva": { height: "170cm", reach: "175cm", wins: 13, losses: 2, draws: 0, stance: "Orthodox", nickname: "Lord" },
    "Cub Swanson": { height: "173cm", reach: "178cm", wins: 29, losses: 14, draws: 0, stance: "Orthodox", nickname: "Killer" },
    "Doo Ho Choi": { height: "175cm", reach: "178cm", wins: 15, losses: 4, draws: 1, stance: "Orthodox", nickname: "The Korean Superboy" },
    "Andre Fili": { height: "180cm", reach: "188cm", wins: 23, losses: 11, draws: 0, stance: "Orthodox", nickname: "Touchy" },
    "Alex Caceres": { height: "178cm", reach: "187cm", wins: 21, losses: 15, draws: 0, stance: "Southpaw", nickname: "Bruce Leeroy" },
    "Sean O'Malley": { height: "180cm", reach: "183cm", wins: 18, losses: 1, draws: 0, stance: "Switch", nickname: "Suga" },
    "Merab Dvalishvili": { height: "168cm", reach: "173cm", wins: 18, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Machine" },
    "Cory Sandhagen": { height: "180cm", reach: "178cm", wins: 17, losses: 5, draws: 0, stance: "Switch", nickname: "The Sandman" },
    "Umar Nurmagomedov": { height: "173cm", reach: "175cm", wins: 18, losses: 0, draws: 0, stance: "Orthodox" },
    "Petr Yan": { height: "170cm", reach: "170cm", wins: 17, losses: 5, draws: 0, stance: "Switch", nickname: "No Mercy" },
    "Marlon Vera": { height: "173cm", reach: "179cm", wins: 23, losses: 9, draws: 1, stance: "Switch", nickname: "Chito" },
    "Henry Cejudo": { height: "163cm", reach: "163cm", wins: 16, losses: 4, draws: 0, stance: "Orthodox", nickname: "Triple C" },
    "Deiveson Figueiredo": { height: "165cm", reach: "173cm", wins: 23, losses: 3, draws: 1, stance: "Orthodox", nickname: "Deus Da Guerra" },
    "Song Yadong": { height: "173cm", reach: "170cm", wins: 21, losses: 8, draws: 1, stance: "Orthodox", nickname: "Kung Fu Kid" },
    "Rob Font": { height: "173cm", reach: "182cm", wins: 20, losses: 8, draws: 0, stance: "Orthodox" },
    "Mario Bautista": { height: "175cm", reach: "175cm", wins: 14, losses: 2, draws: 0, stance: "Switch" },
    "Jonathan Martinez": { height: "173cm", reach: "178cm", wins: 19, losses: 5, draws: 0, stance: "Southpaw", nickname: "Dragon" },
    "Kyler Phillips": { height: "173cm", reach: "183cm", wins: 12, losses: 2, draws: 0, stance: "Switch", nickname: "Matrix" },
    "Dominick Cruz": { height: "173cm", reach: "173cm", wins: 24, losses: 4, draws: 0, stance: "Switch", nickname: "The Dominator" },
    "Pedro Munhoz": { height: "168cm", reach: "165cm", wins: 20, losses: 9, draws: 0, stance: "Orthodox", nickname: "The Young Punisher" },
    "Montel Jackson": { height: "178cm", reach: "191cm", wins: 14, losses: 2, draws: 0, stance: "Southpaw", nickname: "Quik" },
    "Said Nurmagomedov": { height: "173cm", reach: "178cm", wins: 18, losses: 3, draws: 0, stance: "Orthodox" },
    "Youssef Zalal": { height: "178cm", reach: "183cm", wins: 14, losses: 5, draws: 1, stance: "Switch", nickname: "The Moroccan Devil" },
    "Raul Rosas Jr.": { height: "175cm", reach: "170cm", wins: 9, losses: 1, draws: 0, stance: "Switch", nickname: "El Nino Problema" },
    "Payton Talbott": { height: "178cm", reach: "179cm", wins: 8, losses: 0, draws: 0, stance: "Switch" },
    "Cameron Saaiman": { height: "173cm", reach: "170cm", wins: 9, losses: 2, draws: 0, stance: "Southpaw", nickname: "MSP" },
    "Farid Basharat": { height: "173cm", reach: "180cm", wins: 12, losses: 0, draws: 0, stance: "Orthodox", nickname: "Ferocious" },
    "Javid Basharat": { height: "175cm", reach: "175cm", wins: 14, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Snow Leopard" },
    "Taylor Lapilus": { height: "173cm", reach: "185cm", wins: 20, losses: 4, draws: 0, stance: "Southpaw", nickname: "Double Impact" },
    "Daniel Marcos": { height: "170cm", reach: "175cm", wins: 16, losses: 0, draws: 0, stance: "Orthodox", nickname: "Soncora" },
    "Vinicius Oliveira": { height: "175cm", reach: "179cm", wins: 20, losses: 4, draws: 0, stance: "Switch", nickname: "Lok Dog" },
    "Ricky Turcios": { height: "175cm", reach: "180cm", wins: 12, losses: 4, draws: 0, stance: "Orthodox" },
    "Cody Garbrandt": { height: "170cm", reach: "166cm", wins: 14, losses: 6, draws: 0, stance: "Orthodox", nickname: "No Love" },
    "Miles Johns": { height: "170cm", reach: "168cm", wins: 15, losses: 2, draws: 0, stance: "Orthodox", nickname: "Chapo" },
    "Da'Mon Blackshear": { height: "178cm", reach: "183cm", wins: 14, losses: 7, draws: 1, stance: "Switch", nickname: "Da Monster" },
    "Aiemann Zahabi": { height: "173cm", reach: "173cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox" },
    "Marcus McGhee": { height: "173cm", reach: "175cm", wins: 9, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Maniac" },
    "Rani Yahya": { height: "168cm", reach: "170cm", wins: 28, losses: 11, draws: 1, stance: "Orthodox" },
    "Kyung Ho Kang": { height: "175cm", reach: "185cm", wins: 19, losses: 10, draws: 0, stance: "Orthodox", nickname: "Mr. Perfect" },
    "Davey Grant": { height: "173cm", reach: "175cm", wins: 13, losses: 7, draws: 0, stance: "Orthodox", nickname: "Dangerous" },
    "Chris Gutierrez": { height: "175cm", reach: "175cm", wins: 20, losses: 6, draws: 2, stance: "Orthodox", nickname: "El Guapo" },
    "Alexandre Pantoja": { height: "165cm", reach: "170cm", wins: 28, losses: 5, draws: 0, stance: "Orthodox", nickname: "The Cannibal" },
    "Brandon Royval": { height: "175cm", reach: "178cm", wins: 16, losses: 7, draws: 0, stance: "Southpaw", nickname: "Raw Dawg" },
    "Brandon Moreno": { height: "170cm", reach: "178cm", wins: 21, losses: 8, draws: 2, stance: "Orthodox", nickname: "The Assassin Baby" },
    "Amir Albazi": { height: "165cm", reach: "173cm", wins: 17, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Prince" },
    "Kai Kara-France": { height: "163cm", reach: "175cm", wins: 24, losses: 11, draws: 0, stance: "Orthodox", nickname: "Don't Blink" },
    "Matheus Nicolau": { height: "168cm", reach: "168cm", wins: 19, losses: 4, draws: 1, stance: "Orthodox" },
    "Tatsuro Taira": { height: "170cm", reach: "178cm", wins: 15, losses: 0, draws: 0, stance: "Orthodox" },
    "Manel Kape": { height: "165cm", reach: "173cm", wins: 19, losses: 6, draws: 0, stance: "Southpaw", nickname: "Starboy" },
    "Steve Erceg": { height: "173cm", reach: "178cm", wins: 12, losses: 2, draws: 0, stance: "Orthodox", nickname: "Astroboy" },
    "Tim Elliott": { height: "170cm", reach: "168cm", wins: 20, losses: 13, draws: 1, stance: "Southpaw" },
    "Tagir Ulanbekov": { height: "170cm", reach: "178cm", wins: 15, losses: 2, draws: 0, stance: "Southpaw" },
    "Alex Perez": { height: "168cm", reach: "166cm", wins: 25, losses: 8, draws: 0, stance: "Orthodox" },
    "Matt Schnell": { height: "173cm", reach: "178cm", wins: 16, losses: 8, draws: 0, stance: "Orthodox", nickname: "Danger" },
    "Cody Durden": { height: "170cm", reach: "170cm", wins: 16, losses: 5, draws: 1, stance: "Southpaw" },
    "Sumudaerji": { height: "173cm", reach: "183cm", wins: 16, losses: 6, draws: 0, stance: "Southpaw", nickname: "The Tibetan Eagle" },
    "David Dvorak": { height: "165cm", reach: "173cm", wins: 20, losses: 6, draws: 0, stance: "Orthodox", nickname: "Undertaker" },
    "Charles Johnson": { height: "175cm", reach: "178cm", wins: 14, losses: 6, draws: 0, stance: "Switch", nickname: "InnerG" },
    "Azat Maksum": { height: "170cm", reach: "173cm", wins: 17, losses: 1, draws: 0, stance: "Southpaw", nickname: "Kazakh" },
    "Joshua Van": { height: "165cm", reach: "165cm", wins: 10, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Fearless" },
    "Felipe dos Santos": { height: "170cm", reach: "178cm", wins: 8, losses: 1, draws: 0, stance: "Orthodox", nickname: "Lipe Detona" },
    "Allan Nascimento": { height: "175cm", reach: "178cm", wins: 20, losses: 6, draws: 0, stance: "Orthodox", nickname: "Puro Osso" },
    "Jafel Filho": { height: "170cm", reach: "174cm", wins: 16, losses: 3, draws: 0, stance: "Orthodox", nickname: "Pastor" },
    "Assu Almabayev": { height: "163cm", reach: "165cm", wins: 19, losses: 2, draws: 0, stance: "Orthodox", nickname: "Zulfikar" },
    "Park Hyun-sung": { height: "173cm", reach: "175cm", wins: 9, losses: 0, draws: 0, stance: "Orthodox", nickname: "Peace of Mind" },
    "Rei Tsuruya": { height: "168cm", reach: "173cm", wins: 9, losses: 0, draws: 0, stance: "Orthodox" },
    "Igor Severino": { height: "170cm", reach: "173cm", wins: 8, losses: 1, draws: 0, stance: "Orthodox" },
    "Andre Lima": { height: "175cm", reach: "175cm", wins: 8, losses: 0, draws: 0, stance: "Orthodox", nickname: "Mascote" },
    "Clayton Carpenter": { height: "168cm", reach: "173cm", wins: 7, losses: 0, draws: 0, stance: "Orthodox" },
    "Zhang Weili": { height: "163cm", reach: "160cm", wins: 25, losses: 3, draws: 0, stance: "Switch", nickname: "Magnum" },
    "Tatiana Suarez": { height: "165cm", reach: "168cm", wins: 11, losses: 1, draws: 0, stance: "Southpaw" },
    "Yan Xiaonan": { height: "165cm", reach: "160cm", wins: 19, losses: 5, draws: 0, stance: "Orthodox", nickname: "Fury" },
    "Virna Jandiroba": { height: "160cm", reach: "163cm", wins: 22, losses: 3, draws: 0, stance: "Orthodox", nickname: "Carcara" },
    "Amanda Lemos": { height: "163cm", reach: "165cm", wins: 15, losses: 4, draws: 1, stance: "Orthodox", nickname: "Amandinha" },
    "Mackenzie Dern": { height: "163cm", reach: "160cm", wins: 15, losses: 5, draws: 0, stance: "Orthodox" },
    "Loopy Godinez": { height: "157cm", reach: "155cm", wins: 12, losses: 4, draws: 0, stance: "Orthodox" },
    "Tabatha Ricci": { height: "157cm", reach: "155cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox", nickname: "Baby Shark" },
    "Angela Hill": { height: "160cm", reach: "163cm", wins: 17, losses: 13, draws: 0, stance: "Orthodox", nickname: "Overkill" },
    "Luana Pinheiro": { height: "157cm", reach: "157cm", wins: 11, losses: 3, draws: 0, stance: "Orthodox" },
    "Gillian Robertson": { height: "165cm", reach: "160cm", wins: 14, losses: 8, draws: 0, stance: "Orthodox", nickname: "The Savage" },
    "Polyana Viana": { height: "170cm", reach: "170cm", wins: 13, losses: 7, draws: 0, stance: "Orthodox", nickname: "Dama de Ferro" },
    "Emily Ducote": { height: "157cm", reach: "160cm", wins: 13, losses: 9, draws: 0, stance: "Orthodox", nickname: "Gordinha" },
    "Michelle Waterson-Gomez": { height: "160cm", reach: "157cm", wins: 18, losses: 12, draws: 0, stance: "Orthodox", nickname: "The Karate Hottie" },
    "Jessica Andrade": { height: "157cm", reach: "157cm", wins: 26, losses: 13, draws: 0, stance: "Orthodox", nickname: "Bate Estaca" },
    "Marina Rodriguez": { height: "168cm", reach: "165cm", wins: 17, losses: 4, draws: 2, stance: "Orthodox" },
    "Tecia Pennington": { height: "155cm", reach: "155cm", wins: 13, losses: 7, draws: 0, stance: "Orthodox", nickname: "The Tiny Tornado" },
    "Iasmin Lucindo": { height: "160cm", reach: "168cm", wins: 16, losses: 5, draws: 0, stance: "Orthodox" },
    "Alexa Grasso": { height: "165cm", reach: "168cm", wins: 16, losses: 3, draws: 1, stance: "Orthodox" },
    "Valentina Shevchenko": { height: "165cm", reach: "169cm", wins: 25, losses: 4, draws: 1, stance: "Southpaw", nickname: "Bullet" },
    "Manon Fiorot": { height: "170cm", reach: "168cm", wins: 12, losses: 2, draws: 0, stance: "Orthodox", nickname: "The Beast" },
    "Erin Blanchfield": { height: "163cm", reach: "168cm", wins: 13, losses: 2, draws: 0, stance: "Orthodox", nickname: "Cold Blooded" },
    "Rose Namajunas": { height: "165cm", reach: "165cm", wins: 13, losses: 7, draws: 0, stance: "Orthodox", nickname: "Thug" },
    "Mayra Bueno Silva": { height: "168cm", reach: "168cm", wins: 10, losses: 4, draws: 1, stance: "Orthodox", nickname: "Sheetara" },
    "Natalia Silva": { height: "163cm", reach: "165cm", wins: 19, losses: 5, draws: 1, stance: "Southpaw" },
    "Karine Silva": { height: "165cm", reach: "170cm", wins: 18, losses: 4, draws: 0, stance: "Orthodox", nickname: "Killer" },
    "Jasmine Jasudavicius": { height: "170cm", reach: "173cm", wins: 12, losses: 3, draws: 0, stance: "Orthodox" },
    "Ariane Lipski": { height: "168cm", reach: "170cm", wins: 17, losses: 9, draws: 0, stance: "Orthodox", nickname: "Queen of Violence" },
    "Casey O'Neill": { height: "168cm", reach: "175cm", wins: 10, losses: 2, draws: 0, stance: "Orthodox", nickname: "King" },
    "Tracy Cortez": { height: "165cm", reach: "165cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox" },
    "Kayla Harrison": { height: "173cm", reach: "183cm", wins: 19, losses: 1, draws: 0, stance: "Southpaw" },
    "Raquel Pennington": { height: "170cm", reach: "171cm", wins: 16, losses: 9, draws: 0, stance: "Orthodox", nickname: "Rocky" },
    "Julianna Pena": { height: "168cm", reach: "175cm", wins: 13, losses: 6, draws: 0, stance: "Orthodox", nickname: "The Venezuelan Vixen" },
    "Ketlen Vieira": { height: "173cm", reach: "173cm", wins: 14, losses: 4, draws: 0, stance: "Orthodox", nickname: "Fenomeno" },
    "Holly Holm": { height: "173cm", reach: "175cm", wins: 15, losses: 7, draws: 0, stance: "Southpaw", nickname: "The Preacher's Daughter" },
    "Irene Aldana": { height: "175cm", reach: "174cm", wins: 15, losses: 7, draws: 0, stance: "Orthodox" },
    "Macy Chiasson": { height: "180cm", reach: "183cm", wins: 11, losses: 3, draws: 0, stance: "Orthodox" },
    "Pannie Kianzad": { height: "170cm", reach: "168cm", wins: 17, losses: 8, draws: 0, stance: "Orthodox", nickname: "Banzai" },
    "Karol Rosa": { height: "165cm", reach: "170cm", wins: 18, losses: 6, draws: 0, stance: "Orthodox" },
    "Norma Dumont": { height: "170cm", reach: "170cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox", nickname: "The Immortal" },
    "Miesha Tate": { height: "168cm", reach: "165cm", wins: 20, losses: 9, draws: 0, stance: "Orthodox", nickname: "Cupcake" },
    "Ilia Topuria": { height: "170cm", reach: "175cm", wins: 16, losses: 0, draws: 0, stance: "Orthodox", nickname: "El Matador" },
    "Robelis Despaigne": { height: "201cm", reach: "221cm", wins: 5, losses: 1, draws: 0, stance: "Orthodox", nickname: "The Big Boy" },
    "Mick Parkin": { height: "193cm", reach: "201cm", wins: 9, losses: 0, draws: 0, stance: "Orthodox" },
    "Karl Williams": { height: "191cm", reach: "201cm", wins: 10, losses: 1, draws: 0, stance: "Orthodox" },
    "Martin Buday": { height: "193cm", reach: "196cm", wins: 14, losses: 2, draws: 0, stance: "Orthodox", nickname: "Badys" },
    "Caio Machado": { height: "193cm", reach: "198cm", wins: 8, losses: 3, draws: 1, stance: "Southpaw", nickname: "Bigfoot" },
    "Thomas Petersen": { height: "185cm", reach: "188cm", wins: 8, losses: 2, draws: 0, stance: "Southpaw", nickname: "The Train" },
    "Mohammed Usman": { height: "188cm", reach: "201cm", wins: 10, losses: 3, draws: 0, stance: "Orthodox", nickname: "The Motor" },
    "Austen Lane": { height: "198cm", reach: "203cm", wins: 12, losses: 5, draws: 0, stance: "Orthodox" },
    "Jhonata Diniz": { height: "191cm", reach: "196cm", wins: 8, losses: 0, draws: 0, stance: "Orthodox" },
    "Hamdy Abdelwahab": { height: "188cm", reach: "188cm", wins: 5, losses: 0, draws: 0, stance: "Southpaw", nickname: "The Hammer" },
    "Chris Barnett": { height: "175cm", reach: "191cm", wins: 23, losses: 8, draws: 0, stance: "Orthodox", nickname: "Beastboy" },
    "Jamal Pogues": { height: "191cm", reach: "196cm", wins: 11, losses: 4, draws: 0, stance: "Orthodox", nickname: "The Stormtrooper" },
    "Shamil Gaziev": { height: "193cm", reach: "198cm", wins: 12, losses: 1, draws: 0, stance: "Orthodox" },
    "Don'Tale Mayes": { height: "198cm", reach: "206cm", wins: 11, losses: 6, draws: 0, stance: "Orthodox", nickname: "Lord Kong" },
    "Lukasz Brzeski": { height: "193cm", reach: "198cm", wins: 8, losses: 5, draws: 1, stance: "Orthodox", nickname: "The Bull" },
    "Jairzinho Rozenstruik": { height: "188cm", reach: "198cm", wins: 14, losses: 5, draws: 0, stance: "Orthodox", nickname: "Bigi Boy" },
    "Alexandr Romanov": { height: "188cm", reach: "191cm", wins: 17, losses: 3, draws: 0, stance: "Southpaw", nickname: "King Kong" },
    "Marcos Rogerio de Lima": { height: "185cm", reach: "191cm", wins: 22, losses: 9, draws: 1, stance: "Orthodox", nickname: "Pezao" },
    "Rodrigo Nascimento": { height: "191cm", reach: "201cm", wins: 11, losses: 2, draws: 0, stance: "Orthodox", nickname: "Yogi Bear" },
    "Waldo Cortes-Acosta": { height: "193cm", reach: "198cm", wins: 11, losses: 1, draws: 0, stance: "Orthodox", nickname: "Salsa Boy" },
    "Curtis Blaydes": { height: "193cm", reach: "203cm", wins: 18, losses: 5, draws: 0, stance: "Orthodox", nickname: "Razor" },
    "Jailton Almeida": { height: "191cm", reach: "201cm", wins: 20, losses: 3, draws: 0, stance: "Orthodox", nickname: "Malhadinho" },
    "Marcin Tybura": { height: "191cm", reach: "198cm", wins: 25, losses: 8, draws: 0, stance: "Orthodox", nickname: "Tybur" },
    "Alexander Volkov": { height: "201cm", reach: "203cm", wins: 38, losses: 10, draws: 0, stance: "Orthodox", nickname: "Drago" }
};
